
- id: time_to_sleep
  alias: bedtijd
  trigger:
    platform: time
    at: '22:30:00'
  condition:
    - condition: state
      entity_id: input_select.resident_state
      state: 'Home'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.resident_state
      option: 'Sleeping'

- id: slow_lights_bedroom
  alias: zon_op
  trigger:
    platform: time
    at: '06:00:00'
  condition:
    - condition: state
      entity_id: input_select.resident_state
      state: 'Sleeping'
  action:
  - service: script.turn_on
    data:
      entity_id: script.slaapkamer_fade_in


- id: time_to_wake_up
  alias: opstaan
  trigger:
    platform: time
    at: '06:30:00'
  condition:
    - condition: state
      entity_id: input_select.resident_state
      state: 'Sleeping'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.resident_state
      option: 'Home'

- id: some_arrives
  alias: aankomen
  trigger:
    platform: state
    entity_id: group.someone_home
    to: home
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.resident_state
      option: Home

- id: some_leaves
  alias: vertrekken
  trigger:
    platform: state
    entity_id: group.someone_home
    to: not_home
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.resident_state
      option: Away


- id: lights_off_when_not_home
  alias: "niemand thuis"
  trigger:
    platform: state
    entity_id: input_select.resident_state
    from: 'Home'
  action:
    service: homeassistant.turn_off
    entity_id: group.woonkamer_licht


- id: lights_on_when_arrive_home_and_dark
  alias: "iemand komt thuis en het is donker buiten"
  trigger:
    platform: state
    entity_id: input_select.resident_state
    to: 'Home'
  condition:
    condition: numeric_state
    entity_id: sensor.br_irradiance
    below: 150
  action:
    service: scene.turn_on
    entity_id: scene.evening_light


- id: lights_on_when_dark
  alias: "donker buiten.. lichten aan"
  trigger:
    platform: numeric_state
    entity_id: sensor.br_irradiance
    below: 150
  condition:
    condition: state
    entity_id: input_select.resident_state
    state: 'Home'
  action:
    service: scene.turn_on
    entity_id: scene.evening_light

- id: lights_off_when_light_outside
  alias: "zon buiten.. lichten uit"
  trigger:
    platform: numeric_state
    entity_id: sensor.br_irradiance
    above: 150
  action:
    service: homeassistant.turn_off
    entity_id: group.woonkamer_licht
