homeassistant:
  # Name of the location where Home Assistant is running
  name: home
  # Location required to calculate the time the sun rises and sets
  latitude: 52.0733556
  longitude: 5.1339184
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 3
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  customize:
    # hide the following proup
    group.someone_home:
      hidden: true
    # pretty printer icons
    sensor.samsung_clp360_series_192168120:
      friendly_name: samsung CLP-360
      icon: mdi:printer
    sensor.samsung_clp360_series_192168120_toner_black:
      friendly_name: black
      icon: mdi:water
    sensor.samsung_clp360_series_192168120_toner_magenta:
      friendly_name: magenta
      icon: mdi:water
    sensor.samsung_clp360_series_192168120_toner_cyan:
      friendly_name: cyan
      icon: mdi:water
    sensor.samsung_clp360_series_192168120_toner_yellow:
      friendly_name: yellow
      icon: mdi:water
    sensor.samsung_clp360_series_192168120_tray_1:    
      hidden: true

    sensor.document_backup:
      icon: mdi:file-document
    sensor.foto_backup:
      icon: mdi:file-image


# Enables support for tracking state changes over time.
history:
  exclude:
    entities:
      - sensor.since_last_boot

recorder:
  exclude:
    entities:
      - sensor.since_last_boot

      
# Enables the frontend
frontend:

# Enables configuration UI
config:

#show a map
map:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  ssl_certificate: /etc/letsencrypt/live/de-wagnertjes.duckdns.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/de-wagnertjes.duckdns.org/privkey.pem
  base_url: de-wagnertjes.duckdns.org

# Checks for available updates
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
      
# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

#enable MQTT server
mqtt:


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
media_player: !include media_players.yaml
light: !include lights.yaml
zone: !include zones.yaml


#  discovery: true
#  discovery_prefix: homeassistant


binary_sensor:
  - platform: mqtt
    name: hall beweging
    device_class: motion
    state_topic: "home/hall/motion_sensor"


#binary_sensor:
#  - platform: mqtt
#    name: woonkamer beweging microwave
#    device_class: motion
#    state_topic: "home/woonkamer/boekenk    ast/sensor/microwave"
#  - platform: mqtt
#    name: woonkamer beweging pir
#    device_class: motion
#    state_topic: "home/woonkamer/boekenkast/sensor/pir"
#  - platform: template
#    sensors:
#      woonkamer_movement:
#        friendly_name: "woonkamer beweging"
#        delay_off:
#          minutes: 5
#        entity_id:
#          - binary_sensor.woonkamer_beweging_microwave
#          - binary_sensor.woonkamer_beweging_pir
#        device_class: motion
#        value_template: >-
#          {{ is_state('binary_sensor.woonkamer_beweging_pir', 'on') or
#             is_state('binary_sensor.woonkamer_beweging_microwave', 'on')
#          }}

#      someone_home:
#        friendly_name: "iemand_thuis"
#        entity_id:
#           - device_tracker.phonekoosje
#           - device_tracker.phonemarc
#        device_class: presence
#        value_template: >-
#          {{ is_state('device_tracker.phonekoosje', 'home') or
#             is_state('device_tracker.phonemarc', 'home')
#          }}

input_select:
  resident_state:
    name: waar zijn we
    options:
     - Home
     - Away
     - Sleeping
     - Going_Home
    initial: Home
    icon: mdi:home-account

device_tracker:
  - platform: nmap_tracker
    hosts:
      - 192.168.1.32
      - 192.168.1.160
      - 192.168.1.161
      - 192.168.1.162
      - 192.168.1.163
    home_interval: 10
  - platform: gpslogger
    password: !secret gpslogger_password
  - platform: google_maps
    username: wagner.location.sharing@gmail.com@gmail.com
    password: !secret google_location_sharing
   
