homeassistant:
  # Name of the location where Home Assistant is running
  name: home
  # Location required to calculate the time the sun rises and sets
  latitude: 52.0733556
  longitude: 5.1339184
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 3
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam


# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Weather Prediction
sensor:
  platform: yr


# Track the sun
sun:

# Text to speech
tts:
  platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml


#enable MQTT server
mqtt:
#  discovery: true
#  discovery_prefix: homeassistant

 

# test mqtt light switch
light:
  - platform: mqtt_json
    name: woonkamer_tafel
    state_topic: "home/woonkamer/tafel"
    command_topic: "home/woonkamer/tafel/set"
    rgb: true
    brightness: true
    white_value: true
  - platform: mqtt_json
    name: woonkamer_gordijn_kort
    state_topic: "home/woonkamer/gordijn_kort"
    command_topic: "home/woonkamer/gordijn_kort/set"
    rgb: true
    brightness: true
    white_value: true
  - platform: mqtt_json
    name: woonkamer_gordijn_lang
    state_topic: "home/woonkamer/gordijn_lang"
    command_topic: "home/woonkamer/gordijn_lang/set"
    rgb: true
    brightness: true
    white_value: true
  - platform: mqtt
    name: boekenkast rechts
    state_topic: "home/woonkamer/boekenkast/light/light1"
    command_topic: "home/woonkamer/boekenkast/light/light1/set"
    retain: true
  - platform: mqtt
    name: boekenkast links
    state_topic: "home/woonkamer/boekenkast/light/light2"
    command_topic: "home/woonkamer/boekenkast/light/light2/set"
    retain: true
  - platform: mqtt
    name: schermerlamp
    state_topic: "home/woonkamer/bank_schermerlamp"
    command_topic: "home/woonkamer/bank_schermerlamp/set"
    retain: true
  - platform: mqtt
    name: kerstboom
    state_topic: "home/woonkamer/kerstboom"
    command_topic: "home/woonkamer/kerstboom/set"
    retain: true
    
    
  - platform: flux_led
    devices:
      192.168.1.71:
        name: slaapkamer_gordijn
        mode: 'rgb'


binary_sensor:
  - platform: mqtt
    name: woonkamer beweging microwave
    device_class: motion  
    state_topic: "home/woonkamer/boekenkast/sensor/microwave"
  - platform: mqtt
    name: woonkamer beweging pir
    device_class: motion  
    state_topic: "home/woonkamer/boekenkast/sensor/pir"
  - platform: template 
    sensors: 
      woonkamer_movement: 
        friendly_name: "woonkamer beweging"
#        delay_off: 
#          minutes: 5 
        entity_id: 
          - binary_sensor.woonkamer_beweging_microwave
          - binary_sensor.woonkamer_beweging_pir
        device_class: motion
        value_template: >- 
          {{ is_state('binary_sensor.woonkamer_beweging_pir', 'on') or 
          is_state('binary_sensor.woonkamer_beweging_microwave', 'on') 
          }}

#      iemand_thuis:
#        friendly_name: "someone home" 
#        entity_id:
#          - device_tracker.phonemarc
#          - device_tracker.phonekoosje
#        device_class: presence
#        value_template: >- 
#          {{ is_state('device_tracker.phonemarc', 'home') or 
#          is_state(device_tracker.phonekoosje', 'home')
#          }}


#sensor:
  # Tracking entity to entity
#  - platform: google_travel_time
#    name: Phone To Home
#    api_key: !secret google_device_tracker_api_key
#    origin: device_tracker.phonemarc
#    destination: zone.home


# track devices (mobile phones) for presence detetction
device_tracker:
  - platform: ddwrt
    host: 192.168.1.1
    track_new_devices: False
    consider_home: 300
    username: admin
    password: !secret router_password


media_player:
  - platform: mpd
    location: keuken
    friendly_name: muziek keuken
    host: 192.168.1.50
  - platform: mpd
    location: slaapkamer
    friendly_name: muziek slaapkamer
    host: 192.168.1.70
  - platform: cast
    location: woonkamer
    friendly_name: muziek woonkamer
    host: 192.168.1.30
  - platform: cast
    location: woonkamer
    friendly_name: cast woonkamer
    host: 192.168.1.31


#switch:
# -  platform: command_line
#    switches: 
#      wk_servieskast:
#        friendly_name: servieskast
#        command_on: "/home/homeassistant/scripts/switch_broadlink_simplified.py 192.168.1.35 --on"
#        command_off: "/home/homeassistant/scripts/switch_broadlink_simplified.py 192.168.1.35 --off"
#        command_state: "/home/homeassistant/scripts/switch_broadlink_simplified.py 192.168.1.35 --status"
#      wk_boekenkast:
#        friendly_name: boekenkast
#        command_on: "/home/homeassistant/scripts/switch_broadlink_simplified.py 192.168.1.36 --on"
#        command_off: "/home/homeassistant/scripts/switch_broadlink_simplified.py 192.168.1.36 --off"
#        command_state: "/home/homeassistant/scripts/switch_broadlink_simplified.py 192.168.1.36 --status"

switch:
  - platform: broadlink
    host: 192.168.1.35
    mac: B4:43:0D:B9:C1:DD
    type:  sp2
    icon: mdi:lightbulb
    friendly_name: 'servieskast'

#  - platform: broadlink
#    host: 192.168.1.36
#    mac: 34:EA:34:F1:0D:10
#    type:  sp2
#    icon: mdi:lightbulb
#    friendly_name: 'bank schemerlamp'

input_boolean:
  wake_up_slowly_active:
    name: ochtend_alarm_aan
    initial: on
    icon: mdi:alarm-check

